apiVersion: v1
kind: Pod
metadata:
  name: red-pod
  namespace: production
  labels:
    app: web
spec:
  containers:
    - name: webapp-color-container
      image: kodekloud/webapp-color
      env:
        - name: APP_COLOR
          value: "red"
      ports:
        - containerPort: 8080