apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: production
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretRef:
        name: mysql-secret
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-storage
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
