apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-pv